### ISSUE TITLE
Extend the example

### ISSUE THREAD

**Issue by tboenig** [slub/mets-mods2tei#45]
Hi @wrznr,

I thought your program only created TEI metadata. I was just running your example. To avoid this happening to others, I would suggest to extend the example.

MetsMods-Metadata to TEIHeader and skeleton TEI
`(env) $ mm2pc "https://digital.slub-dresden.de/oai/?verb=GetRecord&metadataPrefix=mets&identifier=oai:de:slub-dresden:db:id-453779263"`

MetsMods-Metadata to TEIHeader and OCR text as TEI (using Opion `-o`)
`(env) $ mm2par -o "https://digital.slub-dresden.de/oai/?verb=GetRecord&metadataPrefix=mets&identifier=oai:de:slub-dresden:db:id-453779263"`

**Comment by wrznr** [comment]
Sorry. Not necessary. The documentation, which is admittedly not brilliant, is very clear wrt. `-o`.
