### ISSUE TITLE
Treat CONTENT attribute not only from String elements (but others as well)

### ISSUE THREAD

**Issue by wrznr** [slub/mets-mods2tei#52]
Currently, only CONTENT attributes from `String` are evaluated and realized in the resulting TEI. But ALTO has some other elements which may carry this attribute, most notably `HYP`.

**Comment by bertsky** [comment]
Isn't it also debatable whether it is correct to just join all `TextLine/String` like so?

https://github.com/slub/mets-mods2tei/blob/fc7b0f7cfb8a58e483bd355a7ae2eaaa7aebc6fe/mets_mods2tei/api/alto.py#L95

(I would expect that the white-space joiner only be applied where there is an `SP` interspersed. But there might be different conventions in the field, like having no `SP` at all, i.e. implicit white-space, as in PAGE-XML.)

**Comment by bertsky** [comment]
Regarding `HYP` itself, I'm not sure anymore whether printing `@CONTENT` verbatim is correct: [Basisformat states](https://deutschestextarchiv.de/doku/basisformat/silbentrennung.html) that only hyphen-minus should be allowed.

Maybe make that a config parameter? (We could technically have lots of these; related to #26)
